-- MySQL Script generated by MySQL Workbench
-- Thu Nov 18 14:59:25 2021
-- Model: T6-BancoDeDados   Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
/*

		TRABALHO 6
Alunos: Matheus Silvestre
		Mateus Ries
 Curso: Ciências da computação
 Professor: Lucas Debatin
 
*/
-- -----------------------------------------------------



-- -----------------------------------------------------
-- Schema estacione_aqui
-- -----------------------------------------------------

/*		INICIO QUESTÃO 1		*/
-- -----------------------------------------------------
-- Schema estacione_aqui
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `estacione_aqui` DEFAULT CHARACTER SET utf8 ;
USE `estacione_aqui` ;

-- -----------------------------------------------------
-- Table `estacione_aqui`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estacione_aqui`.`estado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL,
  `uf` VARCHAR(2) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estacione_aqui`.`cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estacione_aqui`.`cidade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_estado` INT NOT NULL,
  `nome` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cidade_estado_idx` (`id_estado` ASC) VISIBLE,
  CONSTRAINT `fk_cidade_estado`
    FOREIGN KEY (`id_estado`)
    REFERENCES `estacione_aqui`.`estado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estacione_aqui`.`patio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estacione_aqui`.`patio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_cidade` INT NOT NULL,
  `logradouro` VARCHAR(200) NULL,
  `numero` INT NULL,
  `bairro` VARCHAR(60) NULL,
  `cep` VARCHAR(9) NULL,
  `capacidade` INT NULL,
  `valor` FLOAT(8,2) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_patio_cidade1_idx` (`id_cidade` ASC) VISIBLE,
  CONSTRAINT `fk_patio_cidade1`
    FOREIGN KEY (`id_cidade`)
    REFERENCES `estacione_aqui`.`cidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estacione_aqui`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estacione_aqui`.`cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NULL,
  `cpf` VARCHAR(14) NULL,
  `data_nascimento` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estacione_aqui`.`modelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estacione_aqui`.`modelo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(50) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estacione_aqui`.`veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estacione_aqui`.`veiculo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_cliente` INT NOT NULL,
  `id_modelo` INT NOT NULL,
  `placa` VARCHAR(9) NULL,
  `cor` VARCHAR(20) NULL,
  `ano` YEAR NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_veiculo_cliente1_idx` (`id_cliente` ASC) VISIBLE,
  INDEX `fk_veiculo_modelo1_idx` (`id_modelo` ASC) VISIBLE,
  CONSTRAINT `fk_veiculo_cliente1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `estacione_aqui`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_veiculo_modelo1`
    FOREIGN KEY (`id_modelo`)
    REFERENCES `estacione_aqui`.`modelo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estacione_aqui`.`ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estacione_aqui`.`ticket` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_veiculo` INT NOT NULL,
  `id_patio` INT NOT NULL,
  `data_entrada` DATETIME NULL,
  `data_saida` DATETIME NULL,
  `valor` FLOAT(8,2) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ticket_veiculo1_idx` (`id_veiculo` ASC) VISIBLE,
  INDEX `fk_ticket_patio1_idx` (`id_patio` ASC) VISIBLE,
  CONSTRAINT `fk_ticket_veiculo1`
    FOREIGN KEY (`id_veiculo`)
    REFERENCES `estacione_aqui`.`veiculo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_patio1`
    FOREIGN KEY (`id_patio`)
    REFERENCES `estacione_aqui`.`patio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

/*		FIM QUESTÃO 1		*/

/*		INICIO QUESTÃO 2		*/

INSERT INTO cliente (nome, cpf, data_nascimento) VALUES
("Ricardo Almeida", "111.111.111-11", "1999/05/23"),
("João Silva", "222.222.222-22", "1975/03/10"),
("Cleiton da Rocha", "333.333.333-33", "1934/12/19"),
("Mario Lopes", "444.444.444-44", "2021/11/18"),
("Silvio Santos", "555.555.555-55", "1874/03/29");

INSERT INTO modelo (descricao) VALUES
("GM Corsa"),
("VW Saveiro"),
("BMW 120i"),
("VW Gol"),
("Ferrari 458"),
("Ford Fiesta"),
("Honda Fit");

INSERT INTO veiculo (id_cliente, id_modelo, placa, cor, ano) VALUES
("1", "1", "AAA-1111", "Preto", "1998"),
("2", "2", "BBB-2222", "Branco", "2018"),
("3", "3", "CCC-3333", "Branco", "2016"),
("4", "4", "DDD-4444", "Azul", "2005"),
("5", "5", "EEE-5555", "Vermelho", "2012"),
("1", "6", "FFF-6666", "Azul", "2009"),
("1", "7", "GGG-7777", "Cinza", "2019");

INSERT INTO estado (nome, uf) VALUES
("Santa Catarina", "SC"),
("Rio Grande Do Sul", "RS"),
("Parana", "PR"),
("São Paulo", "SP"),
("Maranhão", "MA"),
("Bahía", "BA");

INSERT INTO cidade (id_estado, nome) VALUES
("1", "Itajaí"),
("1", "Balneário Camboriú"),
("2", "Curitiba"),
("1", "Florianopolis"),
("2", "Porto Alegre"),
("3", "São José dos Pinhais");

INSERT INTO patio (id_cidade, logradouro, numero, bairro, cep, capacidade, valor) VALUES
("1", "Rua Tijucas", 124, "Centro", "11111-111", 250, 10),
("2", "Rua 3000", 540, "Nações", "22222-222", 120, 25),
("3", "Avenida Central", 23, "Centro", "33333-333", 430, 13.50),
("1", "Rua Brusque", 111, "Centro", "44444-444", 134, 12),
("2", "Rua José", 89, "Murta", "55555-555", 80, 29),
("3", "Avenida Leste", 10, "Centro", "66666-666", 40, 80);


INSERT INTO ticket (id_veiculo, id_patio, data_entrada, data_saida, valor) VALUES
(1, 4, "2021/04/23 19:00:00", "2021/04/23 21:00:00", 15),
(2, 4, "2021/04/14 12:00:00", "2021/04/14 16:30:00", 10),
(3, 4, "2021/02/10 10:00:00", "2021/02/11 13:00:00", 75),
(4, 4, "2021/02/10 12:00:00", "2021/02/10 13:00:00", 10),
(5, 4, "2021/02/23 23:00:00", "2021/02/24 01:00:00", 25),
(6, 4, "2021/07/01 03:00:00", "2021/07/01 13:00:00", 85),
(7, 4, "2021/10/26 14:00:00", "2021/10/27 18:00:00", 130),
(1, 5, "2021/02/15 11:25:00", "2021/02/15 13:00:00", 30),
(1, 6, "2021/11/18 12:00:00", "2021/11/18 13:00:00", 10.50),
(2, 5, "2021/05/11 19:00:00", "2021/05/11 22:00:00", 30);

/*		FIM QUESTÃO 2		*/

/*		INICIO QUESTÃO 3		*/

UPDATE cliente SET cpf = "123.123.123-12" WHERE id = 1;
UPDATE cliente SET nome = "Richarlison Soares" WHERE id = 2;
UPDATE cliente SET data_nascimento = "1958/07/18" WHERE nome = "Silvio Santos";

UPDATE modelo SET descricao = "GM Cruze" WHERE id = 1;
UPDATE modelo SET descricao = "Ferrari 488" WHERE descricao = "Ferrari 458";
UPDATE modelo SET	descricao = "Honda Civic" WHERE id = 6;

UPDATE veiculo SET placa = "ZZZ-8888", cor = "Rosa" WHERE id = 1;
UPDATE veiculo SET id_cliente = 1 WHERE id_cliente = 4;
UPDATE veiculo SET cor="Prata" WHERE id = 6;

UPDATE estado SET uf = "SR" WHERE uf = "RS";
UPDATE estado SET uf = "RS" WHERE id = 1;
UPDATE estado SET uf = "RS" WHERE uf = "SR";
UPDATE estado SET uf = "SC" WHERE id = 1;


UPDATE cidade SET nome = "Itajahi" WHERE nome = "Itajaí";
UPDATE cidade SET id_estado = 3 WHERE nome = "Curitiba";
UPDATE cidade SET nome = "Itajaí" WHERE id = 1;

UPDATE patio SET numero = 322 WHERE id = 4;
UPDATE patio SET capacidade = 240 WHERE capacidade = 250;
UPDATE patio SET valor = 15 WHERE valor = 13.50;

UPDATE ticket SET valor = 125 WHERE id = 17;
UPDATE ticket SET id_patio = 5 where id = 9;
UPDATE ticket SET id_patio = 6 where id = 9;
UPDATE ticket SET data_saida = "2021/02/15 14:00:00" WHERE id = 18;

/*		FIM QUESTÃO 3		*/

/*		INICIO QUESTÃO 4		*/

DELETE FROM ticket WHERE id_veiculo = 5;
DELETE FROM ticket WHERE id_veiculo = 3;
DELETE FROM ticket WHERE id_veiculo = 2;

DELETE FROM veiculo WHERE id = 5;
DELETE FROM veiculo WHERE id = 3;
DELETE FROM veiculo WHERE id = 2;

DELETE FROM modelo WHERE id = 5;
DELETE FROM modelo WHERE id = 3;
DELETE FROM modelo WHERE id = 2;

DELETE FROM cliente WHERE id = 5;
DELETE FROM cliente WHERE id = 3;
DELETE FROM cliente WHERE id = 2;

DELETE FROM patio WHERE id = 1;
DELETE FROM patio WHERE id = 2;
DELETE FROM patio WHERE id = 3;

DELETE FROM cidade WHERE id = 4;
DELETE FROM cidade WHERE id = 5;
DELETE FROM cidade WHERE id = 6;

DELETE FROM estado WHERE id = 4;
DELETE FROM estado WHERE id = 5;
DELETE FROM estado WHERE id = 6;

/*		FIM QUESTÃO 4		*/

/*		INICIO QUESTÃO 5		*/
CREATE USER 'Fausto da Silveira'@'localhost' IDENTIFIED BY '123456';

/*		QUESTÃO 5.1		*/
GRANT SELECT ON estacione_aqui.cidade TO 'Fausto da Silveira'@'localhost';
GRANT SELECT ON estacione_aqui.estado TO 'Fausto da Silveira'@'localhost';
GRANT SELECT ON estacione_aqui.modelo TO 'Fausto da Silveira'@'localhost';

/*		QUESTÃO 5.2		*/
GRANT INSERT, UPDATE, DELETE, SELECT ON estacione_aqui.ticket TO 'Fausto da Silveira'@'localhost';
GRANT INSERT, UPDATE, DELETE, SELECT ON estacione_aqui.veiculo TO 'Fausto da Silveira'@'localhost';
GRANT INSERT, UPDATE, DELETE, SELECT ON estacione_aqui.cliente TO 'Fausto da Silveira'@'localhost';

/*		QUESTÃO 5.3		*/
GRANT INSERT, UPDATE, DELETE ON estacione_aqui.patio TO 'Fausto da Silveira'@'localhost';

/*		QUESTÃO 5.4		*/
REVOKE INSERT, DELETE ON estacione_aqui.patio FROM 'Fausto da Silveira'@'localhost';

/*		FIM QUESTÃO 5		*/

/*		INICIO QUESTÃO 6		*/

/*		QUESTÃO 6.1		*/
SELECT veiculo.placa AS Placa, cliente.nome AS Nome FROM veiculo INNER JOIN cliente ON veiculo.id_cliente = cliente.id;

/*		QUESTÃO 6.2		*/
SELECT COUNT(ticket.id_patio) AS qtd_tickets_SC FROM (((ticket
			INNER JOIN patio ON patio.id = ticket.id_patio) 
            INNER JOIN cidade ON patio.id_cidade = cidade.id)
            INNER JOIN estado ON cidade.id_estado = estado.id)
			WHERE uf="SC";

/*		QUESTÃO 6.3		*/
SELECT veiculo.placa, veiculo.cor, veiculo.ano, modelo.descricao FROM veiculo  
			INNER JOIN modelo ON veiculo.id_modelo = modelo.id
			WHERE ano >= 2010;

/*		QUESTÃO 6.4		*/
SELECT cliente.cpf FROM ((cliente
			INNER JOIN veiculo ON veiculo.id_cliente = cliente.id)
            INNER JOIN modelo ON modelo.id = veiculo.id_modelo)
            WHERE modelo.descricao  LIKE '%Fiat%';
			
/*		QUESTÃO 6.5		*/
SELECT cliente.nome AS Nome, ticket.data_entrada AS Entrada, ticket.data_saida AS Saida FROM ((ticket
			INNER JOIN veiculo ON veiculo.id = ticket.id_veiculo)
            INNER JOIN cliente ON cliente.id = veiculo.id_cliente)
			WHERE DATE_ADD(ticket.data_entrada, interval 3 hour) > ticket.data_saida
            ORDER BY cliente.nome ASC;
 
/*		QUESTÃO 6.6		*/
SELECT SUM(ticket.valor) AS ValorGasto, cliente.nome AS Nome  FROM ((cliente
			INNER JOIN veiculo ON veiculo.id_cliente = cliente.id)
            INNER JOIN ticket ON ticket.id_veiculo = veiculo.id)
			GROUP BY Nome
            ORDER BY ValorGasto DESC, Nome ASC;
            
/*		QUESTÃO 6.7		*/
SELECT veiculo.placa AS Placa, cliente.nome AS NomeCliente, modelo.descricao AS DescricaoModelo FROM ((cliente
			INNER JOIN veiculo ON veiculo.id_cliente = cliente.id)
            INNER JOIN modelo ON modelo.id = veiculo.id_modelo)
			ORDER BY Placa ASC;
            
/*		QUESTÃO 6.8		*/
SELECT veiculo.placa AS Placa, ticket.data_entrada AS Entrada, ticket.data_saida AS Saida FROM ticket
			INNER JOIN veiculo ON veiculo.id = ticket.id_veiculo
            WHERE veiculo.cor = 'Azul';

/*		QUESTÃO 6.9		*/ 
SELECT veiculo.id AS Veiculo, COUNT(DISTINCT ticket.id_patio) AS QTD_Patio FROM veiculo
			INNER JOIN ticket ON ticket.id_veiculo = veiculo.id
            GROUP BY Veiculo;

/*		QUESTÃO 6.10		*/ 
SELECT cliente.nome AS NomeCliente, COUNT(modelo.descricao) AS QTD, modelo.descricao AS NomeVeiculo FROM cliente
			INNER JOIN veiculo ON veiculo.id_cliente = cliente.id
            INNER JOIN modelo ON veiculo.id_modelo = modelo.id
            INNER JOIN ticket ON veiculo.id = ticket.id_veiculo
            GROUP BY modelo.descricao
            ORDER BY QTD DESC
            LIMIT 0,1;
 
/*		FIM QUESTÃO 6		*/
















